# Generated by Django 2.0 on 2018-11-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawltaskmodel',
            name='success_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预约成功时间'),
        ),
        migrations.AlterField(
            model_name='crawltaskmodel',
            name='access_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='接收预约结果的邮箱'),
        ),
        migrations.AlterField(
            model_name='crawltaskmodel',
            name='recommend',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='crawltaskmodel',
            name='stay_address',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='预约地址'),
        ),
        migrations.AlterField(
            model_name='crawltaskmodel',
            name='town',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], default='', max_length=32, verbose_name='镇'),
        ),
    ]
